version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=33060
      - DB_USER=root
      - DB_PASSWORD=123456
    depends_on:
      - database

  database:
    image: mysql:8.0.32
    container_name: bemobile_db
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db_bemobile
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

networks:
  api:
    driver: bridge